name: Run test for code style

on: [push]

jobs:
  PyLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: poetry install

      - name: Test lint
        run: make lint
